
services:

# --- DB ---

  pgadmin:
    image: dpage/pgadmin4

  catalog.database:
    image: postgres:16

  basket.database:
    image: mongo:8.3

  basket.cache:
    image: redis


# --- API ---

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog-service
    build:
      context: .
      dockerfile: src/Services/Catalog/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basket-service
    build:
      context: .
      dockerfile: src/Services/Basket/Dockerfile


volumes:
  catalog_db:
  basket_db:
