name: CI/CD Pipeline

# Branch filtering for commands
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Allow the pipeline to read the repository contents, as well as the right to publish and update. (GitHub Container Registry (ghcr.io))
permissions:
  contents: read
  packages: write

jobs:
  # === STAGE 1: CI (NuGet caching & Test) ===
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    # Caching NuGet packages for accelerate subsequent pipeline runs
    - name: Cache NuGet packages
      uses: actions/cache@v4
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.sln') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - name: Restore dependencies
      run: dotnet restore Ecommerce-Shop.sln

    - name: Build Solution
      run: dotnet build Ecommerce-Shop.sln --no-restore --configuration Release

    # Run all tests (Unit and Integration)
    - name: Run Tests
      run: dotnet test Ecommerce-Shop.sln --no-build --configuration Release --verbosity normal

  # === STAGE 2: CI (Docker Build & Push) ===
  deploy-images:
    needs: build-and-test
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Authenticate with GitHub Container Registry (ghcr.io) using the built-in token
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Convert the repository name to lowercase (Docker requirement for tags)
    - name: Downcase repository name
      run: |
        echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

    # Building and deploying the Catalog microservice
    - name: Build and Push Catalog Service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Services/Catalog/Dockerfile 
        push: true
        tags: ghcr.io/${{ env.REPO_LOWER }}/catalog-service:latest

    # Building and deploying the Basket microservice
    - name: Build and Push Basket Service
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./src/Services/Basket/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_LOWER }}/basket-service:latest

